version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: credit_jambo_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: credit_jambo_client
    ports:
      - "5431:5431"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: credit_jambo_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: